# Generated by Django 5.2.4 on 2025-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chef_dishes/'),
        ),
    ]
