# Generated by Django 5.2.4 on 2025-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_chef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
