# Generated by Django 5.2.4 on 2025-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_chef_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chef_dishes/'),
        ),
    ]
