# Generated by Django 5.2.4 on 2025-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_chef_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='price_per_hour',
            new_name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='profile_image',
        ),
    ]
