# Generated by Django 5.2.4 on 2025-08-22 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_price_per_hour_chef_price_per_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='team_members',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
