# Generated by Django 5.2.4 on 2025-08-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_chef_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hours',
            new_name='person',
        ),
    ]
