# Generated by Django 5.2.4 on 2026-02-11 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='booking_boo_date_f02e27_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='booking_boo_status_6f8d87_idx'),
        ),
    ]
